import React, { useState } from 'react';
import { useSessionReport, ReportEntry, ReportTable } from '../../context/SessionReportContext';
import { useStore } from '../../store/useStore';
import { Printer, Clipboard, Trash2, FileText, Check, Download, AlertCircle, RefreshCw } from 'lucide-react';
import { safeDownloadFile, copyTextToClipboard } from '../../lib/utils';

export default function SessionReport() {
  const { entries, removeFromReport, clearReport } = useSessionReport();
  const { addToast, user } = useStore();
  const [copiedLatexId, setCopiedLatexId] = useState<string | null>(null);
  const [copiedAllLatex, setCopiedAllLatex] = useState(false);

  // LaTeX Document Generation
  const generateLaTeXDocument = (reportEntries: ReportEntry[]) => {
    let doc = `% Generated by Economics Learning Lab (Beta) - Session Report\n`;
    doc += `% Date: ${new Date().toLocaleString()}\n`;
    doc += `\\documentclass[12pt]{article}\n`;
    doc += `\\usepackage{booktabs} % For professional-quality tables\n`;
    doc += `\\usepackage{geometry}\n`;
    doc += `\\geometry{a4paper, margin=1in}\n`;
    doc += `\\usepackage{times} % Times New Roman font\n`;
    doc += `\\usepackage{setspace}\n`;
    doc += `\\usepackage{hyperref}\n`;
    doc += `\\doublespacing\n\n`;
    doc += `\\title{Economics Analysis Session Report}\n`;
    doc += `\\author{Economics Researcher ${user?.email ? `\\\\ \\normalsize (${user.email})` : ''}}\n`;
    doc += `\\date{\\today}\n\n`;
    doc += `\\begin{document}\n`;
    doc += `\\maketitle\n\n`;
    doc += `\\begin{abstract}\n`;
    doc += `This session report compiles multiple empirical models estimated during the active workspace session. `;
    doc += `All models are presented with fully robust standards, design-corrected parameters, or specified lag structures, conforming to standard AEA reporting guidelines.\n`;
    doc += `\\end{abstract}\n\n`;
    doc += `\\clearpage\n\n`;

    reportEntries.forEach((entry, idx) => {
      const escapedTitle = entry.title
        .replace(/%/g, '\\%')
        .replace(/\$/g, '\\$')
        .replace(/&/g, '\\&')
        .replace(/_/g, '\\_')
        .replace(/#/g, '\\#');

      doc += `\\section{${entry.moduleType}: ${escapedTitle}}\n`;
      doc += `\\noindent\\textit{Estimation Date: ${entry.timestamp.toLocaleString()}}\\\\\n\n`;

      if (entry.notes && entry.notes.length > 0) {
        doc += `\\subsection*{Academic Interpretation \& Notes}\n`;
        entry.notes.forEach((note) => {
          const escapedNote = note
            .replace(/%/g, '\\%')
            .replace(/\$/g, '\\$')
            .replace(/&/g, '\\&')
            .replace(/_/g, '\\_')
            .replace(/#/g, '\\#');
          doc += `${escapedNote}\\\\\n`;
        });
        doc += `\n`;
      }

      entry.tables.forEach((table) => {
        const colCount = table.headers.length;
        const alignment = 'l' + 'r'.repeat(colCount - 1);
        const escapedTableTitle = table.title
          .replace(/%/g, '\\%')
          .replace(/\$/g, '\\$')
          .replace(/&/g, '\\&')
          .replace(/_/g, '\\_')
          .replace(/#/g, '\\#');

        doc += `\\begin{table}[htbp]\n`;
        doc += `\\centering\n`;
        doc += `\\caption{${escapedTableTitle}}\n`;
        doc += `\\begin{tabular}{${alignment}}\n`;
        doc += `\\toprule\n`;
        
        // Headers
        const escapedHeaders = table.headers.map(h => 
          h.replace(/%/g, '\\%')
           .replace(/\$/g, '\\$')
           .replace(/&/g, '\\&')
           .replace(/_/g, '\\_')
           .replace(/#/g, '\\#')
        );
        doc += `${escapedHeaders.join(' & ')} \\\\\n`;
        doc += `\\midrule\n`;
        
        // Rows
        table.rows.forEach((row) => {
          const escapedRow = row.map(cell => {
            if (cell === null || cell === undefined) return '';
            const strCell = typeof cell === 'number' ? cell.toFixed(4) : String(cell);
            return strCell
              .replace(/%/g, '\\%')
              .replace(/\$/g, '\\$')
              .replace(/&/g, '\\&')
              .replace(/_/g, '\\_')
              .replace(/#/g, '\\#');
          });
          doc += `${escapedRow.join(' & ')} \\\\\n`;
        });
        
        doc += `\\bottomrule\n`;
        doc += `\\end{tabular}\n`;
        
        if (table.footnote) {
          const escapedFootnote = table.footnote
            .replace(/%/g, '\\%')
            .replace(/\$/g, '\\$')
            .replace(/&/g, '\\&')
            .replace(/_/g, '\\_')
            .replace(/#/g, '\\#');
          doc += `\\\\\n\\vspace{1mm}\n\\raggedright\\scriptsize\\textit{Note:} ${escapedFootnote}\n`;
        }
        
        doc += `\\end{table}\n\n`;
      });

      if (idx < reportEntries.length - 1) {
        doc += `\\clearpage\n\n`;
      }
    });

    doc += `\\end{document}\n`;
    return doc;
  };

  const handleCopyLaTeXAll = () => {
    if (entries.length === 0) {
      addToast('info', 'LaTeX Export', 'No entries to export.');
      return;
    }
    const doc = generateLaTeXDocument(entries);
    copyTextToClipboard(doc).then((success) => {
      if (success) {
        setCopiedAllLatex(true);
        addToast('success', 'LaTeX Copied', 'Full LaTeX session document copied to clipboard.');
        setTimeout(() => setCopiedAllLatex(false), 2000);
      } else {
        addToast('error', 'LaTeX Failed', 'Could not copy to clipboard.');
      }
    });
  };

  const handleCopyLaTeXSingle = (entry: ReportEntry) => {
    const doc = generateLaTeXDocument([entry]);
    copyTextToClipboard(doc).then((success) => {
      if (success) {
        setCopiedLatexId(entry.id);
        addToast('success', 'LaTeX Copied', `Model LaTeX copied for: ${entry.title}`);
        setTimeout(() => setCopiedLatexId(null), 2000);
      } else {
        addToast('error', 'LaTeX Failed', 'Could not copy to clipboard.');
      }
    });
  };

  const handlePrintPDF = () => {
    if (entries.length === 0) {
      addToast('info', 'Print Cancelled', 'No analysis entries in report to print.');
      return;
    }
    document.body.classList.add('printing-academic-report');
    const cleanup = () => {
      document.body.classList.remove('printing-academic-report');
      window.removeEventListener('afterprint', cleanup);
    };
    window.addEventListener('afterprint', cleanup);
    setTimeout(() => {
      window.print();
      setTimeout(cleanup, 1000);
    }, 150);
  };

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-8 no-print font-sans">
      {/* Header Panel */}
      <div className="bg-slate-900 text-slate-100 rounded-3xl p-8 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-6 border border-slate-800">
        <div className="space-y-2">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-blue-500 flex items-center justify-center">
              <FileText className="w-4 h-4 text-white" />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-white font-serif">Academic Output Session Report</h1>
          </div>
          <p className="text-xs text-slate-400 font-serif italic max-w-xl">
            Saves and formats your models sequentially. Emulates SPSS Output Viewer with standard American Economic Association (AEA) formatting, Times New Roman display rendering, and raw LaTeX exporting capabilities.
          </p>
        </div>

        {entries.length > 0 && (
          <div className="flex flex-wrap items-center gap-3">
            <button
              onClick={handlePrintPDF}
              className="px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-semibold tracking-wider uppercase transition-all shadow-md flex items-center gap-2 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5 text-blue-100" />
              Export PDF (Print)
            </button>
            <button
              onClick={handleCopyLaTeXAll}
              className={`px-4 py-2.5 rounded-xl text-xs font-semibold tracking-wider uppercase transition-all shadow-md flex items-center gap-2 cursor-pointer border ${
                copiedAllLatex
                  ? 'bg-emerald-500 border-emerald-500 text-white'
                  : 'bg-slate-800 border-slate-700 text-slate-100 hover:bg-slate-700'
              }`}
            >
              {copiedAllLatex ? <Check className="w-3.5 h-3.5" /> : <Clipboard className="w-3.5 h-3.5" />}
              {copiedAllLatex ? 'Copied Full Document!' : 'Copy LaTeX Document'}
            </button>
            <button
              onClick={clearReport}
              className="px-4 py-2.5 bg-rose-600/10 border border-rose-500/20 text-rose-400 hover:bg-rose-600 hover:text-white rounded-xl text-xs font-semibold tracking-wider uppercase transition-all flex items-center gap-2 cursor-pointer"
            >
              <Trash2 className="w-3.5 h-3.5" />
              Clear All
            </button>
          </div>
        )}
      </div>

      {/* Main Content Area */}
      {entries.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-24 px-6 text-center bg-white border border-slate-100 rounded-3xl shadow-sm space-y-6">
          <div className="p-5 bg-slate-50 rounded-full border border-slate-100">
            <FileText className="w-12 h-12 text-slate-300 stroke-1" />
          </div>
          <div className="space-y-2 max-w-md">
            <h3 className="text-sm font-bold uppercase tracking-widest text-slate-700 font-mono">Report Vault is Empty</h3>
            <p className="text-xs text-slate-400 font-serif italic leading-relaxed">
              Run econometrics models across tabs (Linear Models, Panel Data, ARIMA, Causal Labs) and click "Add to Report" inside the results panel. This aggregates all data into an active scholarly compendium.
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-8">
          {entries.map((entry, index) => (
            <div
              key={entry.id}
              className="bg-white border border-slate-200/80 rounded-3xl p-8 shadow-sm hover:shadow-md transition-all space-y-6 relative group"
            >
              {/* Header card */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-slate-100 gap-4">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[9px] font-bold text-blue-600 bg-blue-50 border border-blue-100 px-2 py-0.5 rounded-md uppercase tracking-wider font-mono">
                      {entry.moduleType}
                    </span>
                    <span className="text-[10px] text-slate-400 font-mono">
                      {entry.timestamp.toLocaleString()}
                    </span>
                  </div>
                  <h2 className="text-base font-bold text-slate-900 font-serif">
                    Model {index + 1}: {entry.title}
                  </h2>
                </div>

                <div className="flex items-center gap-2 opacity-90 group-hover:opacity-100 transition-opacity">
                  <button
                    onClick={() => handleCopyLaTeXSingle(entry)}
                    className={`p-2 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 border cursor-pointer ${
                      copiedLatexId === entry.id
                        ? 'bg-emerald-50 border-emerald-200 text-emerald-700'
                        : 'bg-slate-50 hover:bg-slate-100 border-slate-200 text-slate-600'
                    }`}
                    title="Copy this single model as a LaTeX block"
                  >
                    {copiedLatexId === entry.id ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-600" />
                        <span className="text-[10px] uppercase font-bold tracking-wider font-mono">Copied!</span>
                      </>
                    ) : (
                      <>
                        <Clipboard className="w-3.5 h-3.5 text-slate-400" />
                        <span className="text-[10px] uppercase font-bold tracking-wider font-mono">LaTeX Block</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => removeFromReport(entry.id)}
                    className="p-2 bg-rose-50 hover:bg-rose-100 text-rose-600 rounded-xl transition-all border border-rose-100 cursor-pointer"
                    title="Remove this model entry"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* Notes block */}
              {entry.notes && entry.notes.length > 0 && (
                <div className="p-4 bg-amber-50/40 border border-amber-100 rounded-2xl space-y-1.5">
                  <span className="text-[9px] font-bold text-amber-800 uppercase tracking-wider font-mono">Academic Insights &amp; Interpretation</span>
                  <div className="space-y-1">
                    {entry.notes.map((note, i) => (
                      <p key={i} className="text-xs text-slate-600 font-serif leading-relaxed text-justify">
                        {note}
                      </p>
                    ))}
                  </div>
                </div>
              )}

              {/* Tables */}
              <div className="space-y-6">
                {entry.tables.map((table, tIdx) => (
                  <div key={tIdx} className="space-y-2">
                    <h3 className="text-xs font-bold text-slate-800 tracking-tight font-serif italic">
                      Table {index + 1}.{tIdx + 1}: {table.title}
                    </h3>
                    
                    <div className="overflow-x-auto rounded-xl border border-slate-100 bg-slate-50/30 p-1">
                      <table className="w-full text-left font-mono text-[11px] border-collapse bg-white rounded-lg overflow-hidden shadow-sm">
                        <thead>
                          <tr className="bg-slate-50 border-b border-slate-200 text-slate-700">
                            {table.headers.map((h, hIdx) => (
                              <th
                                key={hIdx}
                                className={`p-2.5 font-bold uppercase tracking-wider text-[9px] border-r border-slate-100 last:border-r-0 ${
                                  hIdx === 0 ? 'text-left' : 'text-right'
                                }`}
                              >
                                {h}
                              </th>
                            ))}
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                          {table.rows.map((row, rIdx) => (
                            <tr key={rIdx} className={rIdx % 2 === 0 ? 'bg-white' : 'bg-slate-50/20'}>
                              {row.map((cell, cIdx) => (
                                <td
                                  key={cIdx}
                                  className={`p-2.5 border-r border-slate-100 last:border-r-0 ${
                                    cIdx === 0 ? 'text-left font-bold text-slate-900' : 'text-right font-semibold text-slate-700'
                                  }`}
                                >
                                  {cell === null || cell === undefined
                                    ? '—'
                                    : typeof cell === 'number'
                                    ? cell.toFixed(4)
                                    : String(cell)}
                                </td>
                              ))}
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>

                    {table.footnote && (
                      <p className="text-[10px] text-slate-400 font-serif italic pl-1 leading-normal">
                        Note: {table.footnote}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Printing guidelines for frame */}
      <div className="p-4 bg-slate-50 border border-slate-200/60 rounded-2xl flex items-start gap-3">
        <AlertCircle className="w-4.5 h-4.5 text-slate-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-600 font-mono">Academic Printing Notice</p>
          <p className="text-[11px] text-slate-500 font-serif italic leading-relaxed">
            For maximum quality and correct margins, make sure to enable <strong>"Background graphics"</strong> and set headers/footers to <strong>"None"</strong> in your browser's Print dialog. If you run into sandboxed container iframe limitations, click the "Open in New Tab" button in the very top right of the workspace.
          </p>
        </div>
      </div>
    </div>
  );
}
