// 
// Static build-time certification constants for Numerical Certification
// Generated by scripts/certify-constants.js from a real Jest run. Do not edit by hand.
export const CERTIFICATION_CONSTANTS = {
  nistPrecisionLRE: 8.97, // Log Relative Error worst-case across all NIST benchmarks
  nistPrecisionDigits: "8.97 digits",
  // Worst-case LRE per NIST dataset, parsed from the same run (null = not measured)
  lrePerDataset: {
    longley: 11.25,
    wampler1: 8.97,
    wampler2: 13.52,
  },
  goldenTestsPassed: 7,
  goldenTestsTotal: 7,
  lastCertifiedDate: "2026-07-19",
  doublePrecisionBits: 64,
};
