import React from 'react';
import { motion } from 'motion/react';
import { X, Shield, FileText, Share2, Scale, Lock, Database } from 'lucide-react';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TermsOfService({ isOpen, onClose }: ModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 15 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 15 }}
        className="relative w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl border border-slate-800 bg-slate-900 text-slate-100 shadow-2xl overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 px-6 py-4 bg-slate-950/40">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400">
              <Scale className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-md font-bold text-slate-100 tracking-tight">Terms of Service</h2>
              <p className="text-[10px] text-slate-400 uppercase tracking-widest font-mono">Academic Agreement</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg border border-slate-800 hover:border-slate-700 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-all"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-6 space-y-5 font-serif text-[13px] text-slate-300 leading-relaxed custom-scrollbar">
          <p className="font-sans font-medium text-slate-400 text-xs">
            Welcome to the Economics Learning Lab (Beta). By using our econometric sandbox, AI tutor desk, and academic planning suite, you agree to comply with and be bound by the following academic terms of service.
          </p>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              1. Non-Commercial Academic Sandbox
            </h3>
            <p>
              The Economics Learning Lab (Beta) is designed solely for educational, research, and preparatory purposes (including MA, UGC-NET, and CUET PG prep). Any output, econometric estimation, or synthesis generated by the platform is intended for teaching and learning; it must not be used for industrial or commercial advice.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              2. Intellectual Property and Attribution
            </h3>
            <p>
              Users retain full ownership of any academic datasets they upload. Synthesized textbook notes, LaTeX templates, and econometric insights generated by our integrated LLM desk are licensed under a Creative Commons Attribution-NonCommercial (CC BY-NC) license. You are free to cite and adapt materials for your personal thesis, examinations, or non-commercial papers provided appropriate attribution to the Lab is given.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              3. No Liability for Empirical Outputs
            </h3>
            <p>
              All quantitative model estimations (OLS regressions, Time-Series ARIMA, and Fixed Effects models) are computed client-side. The pedagogical reviews, policy suggestions, and "strict teacher feedback" are AI-guided and should be cross-referenced with authorized curriculum guidelines, official textbooks, or refereed journals before formal submission.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              4. Code of Academic Conduct
            </h3>
            <p>
              As a serious scholarly tool, we maintain strict adherence to intellectual integrity. You agree to use the platform in compliance with your university's academic honor codes and agree not to submit generated answers as your direct work in active, proctored examinations.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2 border-t border-slate-800 px-6 py-4 bg-slate-950/40">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-sans text-xs font-bold transition-all shadow-lg shadow-emerald-950/20 uppercase tracking-widest"
          >
            I Agree
          </button>
        </div>
      </motion.div>
    </div>
  );
}

export function PrivacyPolicy({ isOpen, onClose }: ModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 15 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 15 }}
        className="relative w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl border border-slate-800 bg-slate-900 text-slate-100 shadow-2xl overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 px-6 py-4 bg-slate-950/40">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400">
              <Lock className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-md font-bold text-slate-100 tracking-tight">Privacy Policy</h2>
              <p className="text-[10px] text-slate-400 uppercase tracking-widest font-mono">Data Stewardship</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg border border-slate-800 hover:border-slate-700 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-all"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-6 space-y-5 font-serif text-[13px] text-slate-300 leading-relaxed custom-scrollbar">
          <p className="font-sans font-medium text-slate-400 text-xs">
            The Economics Learning Lab (Beta) respects the privacy of your empirical inquiries, datasets, and tutoring submissions. We treat academic work with strict confidentiality.
          </p>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              1. Dataset Isolation & In-Memory Estimation
            </h3>
            <p>
              Any econometric datasets (.csv or spreadsheet formats) loaded into the Academic Lab or Stats Sandbox are processed in-memory. They are never permanently archived, distributed, or used to train public machine learning algorithms. All calculations operate entirely inside your safe browser environment.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              2. Chat History & Academic Queries
            </h3>
            <p>
              Academic inquiries processed via the "Professor Desk", "Academic Lab", or "Teacher Mode" are forwarded through secure API pipes to the designated Gemini-3-Flash model. This metadata remains protected and is utilized exclusively to formulate responses and update your offline study record.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              3. Cookie Usage and Client Storage
            </h3>
            <p>
              Your scholar streak, study logs, and configuration preferences (like UI density and academic level) are safely persisted in standard browser localStorage. No tracking pixels, persistent advertisement profiles, or invasive third-party telemetry tools are configured inside this application.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2 border-t border-slate-800 px-6 py-4 bg-slate-950/40">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-sans text-xs font-bold transition-all shadow-lg shadow-emerald-950/20 uppercase tracking-widest"
          >
            Acknowledge
          </button>
        </div>
      </motion.div>
    </div>
  );
}

export function DataAttribution({ isOpen, onClose }: ModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 15 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 15 }}
        className="relative w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl border border-slate-800 bg-slate-900 text-slate-100 shadow-2xl overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 px-6 py-4 bg-slate-950/40">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-md font-bold text-slate-100 tracking-tight">Data Attribution</h2>
              <p className="text-[10px] text-slate-400 uppercase tracking-widest font-mono">Curriculum Acknowledgements</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg border border-slate-800 hover:border-slate-700 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-all"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-6 space-y-5 font-serif text-[13px] text-slate-300 leading-relaxed custom-scrollbar">
          <p className="font-sans font-medium text-slate-400 text-xs">
            The Economics Learning Lab (Beta) aggregates mock datasets, past paper structures, and theoretical insights referencing several premium academic frameworks.
          </p>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              1. Econometric Datasets & Reference Models
            </h3>
            <p>
              Pre-loaded sample models (such as Okun's Law regressions, Philips Curve ARIMA, and Penn World Tables panel specifications) are constructed referencing public datasets curated by the Federal Reserve Bank of St. Louis (FRED), World Bank DataBank, and academic textbook resources by Wooldridge, Stock & Watson, and Baltagi.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              2. UGC-NET & CUET PG Syllabi
            </h3>
            <p>
              Syllabus benchmarks, model prompts, and analytical modes (Topic Overview, Compare & Contrast, Assumption Stress Test) conform directly to the guidelines set forth by the National Testing Agency (NTA), University Grants Commission (UGC) of India, and leading Indian Central Universities.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-sans font-bold text-emerald-400 flex items-center gap-1.5 uppercase text-[11px] tracking-wider">
              3. Vector Assets and UI Design System
            </h3>
            <p>
              Aesthetic illustrations, icons, and display typeface configurations utilize Lucide Open Source Vectors and Google Font licenses. The newly suggested vector brand logo is designed using high-resolution scholarly branding guidelines.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="flex-1 flex-shrink-0 flex items-center justify-end gap-2 border-t border-slate-800 px-6 py-4 bg-slate-950/40">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 font-sans text-xs font-bold transition-all uppercase tracking-widest"
          >
            Close
          </button>
        </div>
      </motion.div>
    </div>
  );
}
